package cn.com.wh.ring.database;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

import cn.com.wh.ring.database.bean.PostPublish;
import cn.com.wh.ring.database.dao.PostPublishDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig postPublishDaoConfig;

    private final PostPublishDao postPublishDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        postPublishDaoConfig = daoConfigMap.get(PostPublishDao.class).clone();
        postPublishDaoConfig.initIdentityScope(type);

        postPublishDao = new PostPublishDao(postPublishDaoConfig, this);

        registerDao(PostPublish.class, postPublishDao);
    }
    
    public void clear() {
        postPublishDaoConfig.clearIdentityScope();
    }

    public PostPublishDao getPostPublishDao() {
        return postPublishDao;
    }

}
