package cn.com.wh.ring.database.bean;

import com.amap.api.location.AMapLocation;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ADDRESS".
 */
@Entity
public class Address {

    @Id(autoincrement = true)
    private Long id;
    private String country;
    private String province;
    private String city;
    private String district;
    private double lng;
    private double lat;

    @Generated(hash = 388317431)
    public Address() {
    }

    public Address(Long id) {
        this.id = id;
    }

    @Generated(hash = 1628422232)
    public Address(Long id, String country, String province, String city, String district, double lng, double lat) {
        this.id = id;
        this.country = country;
        this.province = province;
        this.city = city;
        this.district = district;
        this.lng = lng;
        this.lat = lat;
    }

    public Address(AMapLocation aMapLocation) {
        this.country = aMapLocation.getCountry();
        this.province = aMapLocation.getProvince();
        this.city = aMapLocation.getCity();
        this.district = aMapLocation.getDistrict();
        this.lng = aMapLocation.getLongitude();
        this.lat = aMapLocation.getLatitude();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getDistrict() {
        return district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public double getLng() {
        return lng;
    }

    public void setLng(double lng) {
        this.lng = lng;
    }

    public double getLat() {
        return lat;
    }

    public void setLat(double lat) {
        this.lat = lat;
    }

}
