package cn.com.wh.ring.database.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "POST_PUBLISH".
 */
@Entity
public class PostPublish {
    public static final int STATE_PUBLISHING = -1; //发布中
    public static final int STATE_SUCCESS = -2; //发布成功
    public static final int STATE_FAIL = -3; //发布失败

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String token;

    @NotNull
    private String uuid;
    private String content;
    private String mediaContent;

    @NotNull
    private String type;
    private Boolean anonymous;
    private Integer state;
    private Long addressId;
    private long time;

    @Generated(hash = 521198697)
    public PostPublish() {
    }

    public PostPublish(Long id) {
        this.id = id;
    }

    @Generated(hash = 380020328)
    public PostPublish(Long id, @NotNull String token, @NotNull String uuid, String content, String mediaContent, @NotNull String type, Boolean anonymous, Integer state,
            Long addressId, long time) {
        this.id = id;
        this.token = token;
        this.uuid = uuid;
        this.content = content;
        this.mediaContent = mediaContent;
        this.type = type;
        this.anonymous = anonymous;
        this.state = state;
        this.addressId = addressId;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getToken() {
        return token;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToken(@NotNull String token) {
        this.token = token;
    }

    @NotNull
    public String getUuid() {
        return uuid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUuid(@NotNull String uuid) {
        this.uuid = uuid;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getMediaContent() {
        return mediaContent;
    }

    public void setMediaContent(String mediaContent) {
        this.mediaContent = mediaContent;
    }

    @NotNull
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(@NotNull String type) {
        this.type = type;
    }

    public Boolean getAnonymous() {
        return anonymous;
    }

    public void setAnonymous(Boolean anonymous) {
        this.anonymous = anonymous;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Long getAddressId() {
        return addressId;
    }

    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

}
