package cn.com.wh.ring.database.bean;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "POST_PUBLISH".
 */
@Entity
public class PostPublish {

    @Id
    private Long id;

    @NotNull
    private String userId;
    private String content;
    private String mediaContent;
    private Integer mediaType;
    private int type;
    private long time;
    private Boolean anonymous;

    @Generated(hash = 521198697)
    public PostPublish() {
    }

    public PostPublish(Long id) {
        this.id = id;
    }

    @Generated(hash = 1071372744)
    public PostPublish(Long id, @NotNull String userId, String content, String mediaContent, Integer mediaType, int type, long time,
            Boolean anonymous) {
        this.id = id;
        this.userId = userId;
        this.content = content;
        this.mediaContent = mediaContent;
        this.mediaType = mediaType;
        this.type = type;
        this.time = time;
        this.anonymous = anonymous;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(@NotNull String userId) {
        this.userId = userId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getMediaContent() {
        return mediaContent;
    }

    public void setMediaContent(String mediaContent) {
        this.mediaContent = mediaContent;
    }

    public Integer getMediaType() {
        return mediaType;
    }

    public void setMediaType(Integer mediaType) {
        this.mediaType = mediaType;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public Boolean getAnonymous() {
        return anonymous;
    }

    public void setAnonymous(Boolean anonymous) {
        this.anonymous = anonymous;
    }

}
