package cn.com.wh.ring.database.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "POST_PUBLISH".
 */
@Entity
public class PostPublish {

    @Id
    private Long id;
    private String content;
    private String mediaContent;
    private Integer mediaType;
    private int type;
    private long time;
    private Boolean anonymous;

    @Generated
    public PostPublish() {
    }

    public PostPublish(Long id) {
        this.id = id;
    }

    @Generated
    public PostPublish(Long id, String content, String mediaContent, Integer mediaType, int type, long time, Boolean anonymous) {
        this.id = id;
        this.content = content;
        this.mediaContent = mediaContent;
        this.mediaType = mediaType;
        this.type = type;
        this.time = time;
        this.anonymous = anonymous;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getMediaContent() {
        return mediaContent;
    }

    public void setMediaContent(String mediaContent) {
        this.mediaContent = mediaContent;
    }

    public Integer getMediaType() {
        return mediaType;
    }

    public void setMediaType(Integer mediaType) {
        this.mediaType = mediaType;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public Boolean getAnonymous() {
        return anonymous;
    }

    public void setAnonymous(Boolean anonymous) {
        this.anonymous = anonymous;
    }

}
