package cn.com.wh.ring.database.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "USER_INFO".
 */
@Entity
public class UserInfo {
    public static final int SEX_MAN = 1;
    public static final int SEX_WOMAN = 2;
    public static final int SEX_UN_SELECT = 3;

    @Id(autoincrement = true)
    private Long id;

    @Unique
    private long userId;
    private Long infoId;
    private String nickname;
    private Long birthday;
    private int sex;
    private String avatar;
    private String signature;
    private String addressCode;
    private long lastModifiedTime;

    @Generated(hash = 1279772520)
    public UserInfo() {
    }

    public UserInfo(Long id) {
        this.id = id;
    }

    @Generated(hash = 79733303)
    public UserInfo(Long id, long userId, Long infoId, String nickname, Long birthday, int sex, String avatar, String signature, String addressCode, long lastModifiedTime) {
        this.id = id;
        this.userId = userId;
        this.infoId = infoId;
        this.nickname = nickname;
        this.birthday = birthday;
        this.sex = sex;
        this.avatar = avatar;
        this.signature = signature;
        this.addressCode = addressCode;
        this.lastModifiedTime = lastModifiedTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public Long getInfoId() {
        return infoId;
    }

    public void setInfoId(Long infoId) {
        this.infoId = infoId;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public Long getBirthday() {
        return birthday;
    }

    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    public int getSex() {
        return sex;
    }

    public void setSex(int sex) {
        this.sex = sex;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public String getAddressCode() {
        return addressCode;
    }

    public void setAddressCode(String addressCode) {
        this.addressCode = addressCode;
    }

    public long getLastModifiedTime() {
        return lastModifiedTime;
    }

    public void setLastModifiedTime(long lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    @Override
    public String toString() {
        return "UserInfo{" +
                "id=" + id +
                ", userId=" + userId +
                ", infoId=" + infoId +
                ", nickname='" + nickname + '\'' +
                ", birthday=" + birthday +
                ", sex=" + sex +
                ", avatar='" + avatar + '\'' +
                ", signature='" + signature + '\'' +
                ", addressCode='" + addressCode + '\'' +
                ", lastModifiedTime=" + lastModifiedTime +
                '}';
    }
}
