package cn.com.wh.ring.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.com.wh.ring.database.DaoSession;
import cn.com.wh.ring.database.bean.PostPublish;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "POST_PUBLISH".
*/
public class PostPublishDao extends AbstractDao<PostPublish, Long> {

    public static final String TABLENAME = "POST_PUBLISH";

    /**
     * Properties of entity PostPublish.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Content = new Property(1, String.class, "content", false, "CONTENT");
        public final static Property MediaContent = new Property(2, String.class, "mediaContent", false, "MEDIA_CONTENT");
        public final static Property MediaType = new Property(3, Integer.class, "mediaType", false, "MEDIA_TYPE");
        public final static Property Type = new Property(4, int.class, "type", false, "TYPE");
        public final static Property Time = new Property(5, long.class, "time", false, "TIME");
        public final static Property Anonymous = new Property(6, Boolean.class, "anonymous", false, "ANONYMOUS");
    }


    public PostPublishDao(DaoConfig config) {
        super(config);
    }
    
    public PostPublishDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"POST_PUBLISH\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CONTENT\" TEXT," + // 1: content
                "\"MEDIA_CONTENT\" TEXT," + // 2: mediaContent
                "\"MEDIA_TYPE\" INTEGER," + // 3: mediaType
                "\"TYPE\" INTEGER NOT NULL ," + // 4: type
                "\"TIME\" INTEGER NOT NULL ," + // 5: time
                "\"ANONYMOUS\" INTEGER);"); // 6: anonymous
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"POST_PUBLISH\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PostPublish entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(2, content);
        }
 
        String mediaContent = entity.getMediaContent();
        if (mediaContent != null) {
            stmt.bindString(3, mediaContent);
        }
 
        Integer mediaType = entity.getMediaType();
        if (mediaType != null) {
            stmt.bindLong(4, mediaType);
        }
        stmt.bindLong(5, entity.getType());
        stmt.bindLong(6, entity.getTime());
 
        Boolean anonymous = entity.getAnonymous();
        if (anonymous != null) {
            stmt.bindLong(7, anonymous ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PostPublish entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(2, content);
        }
 
        String mediaContent = entity.getMediaContent();
        if (mediaContent != null) {
            stmt.bindString(3, mediaContent);
        }
 
        Integer mediaType = entity.getMediaType();
        if (mediaType != null) {
            stmt.bindLong(4, mediaType);
        }
        stmt.bindLong(5, entity.getType());
        stmt.bindLong(6, entity.getTime());
 
        Boolean anonymous = entity.getAnonymous();
        if (anonymous != null) {
            stmt.bindLong(7, anonymous ? 1L: 0L);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PostPublish readEntity(Cursor cursor, int offset) {
        PostPublish entity = new PostPublish( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // content
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // mediaContent
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // mediaType
            cursor.getInt(offset + 4), // type
            cursor.getLong(offset + 5), // time
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0 // anonymous
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PostPublish entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setContent(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMediaContent(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMediaType(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setType(cursor.getInt(offset + 4));
        entity.setTime(cursor.getLong(offset + 5));
        entity.setAnonymous(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PostPublish entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PostPublish entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PostPublish entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
